version: '3.5'
services:
    postgres:
        container_name: PSQLTyupko
        image: postgres
        environment:
            POSTGRES_DB: BOLNIZA
            POSTGRES_USER: BOLNIZA
            POSTGRES_PASSWORD: 12345
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./initBD.sql:/docker-entrypoint-initdb.d/initBD.sql
        ports:
            - "5555:5432"
        networks:
            net:
                ipv4_address: 10.5.0.5
        restart: unless-stopped

    pgadmin:
        container_name: PGATyupko
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: student8181455@gmail.com
            PGADMIN_DEFAULT_PASSWORD: 54321
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "5050:80"
        networks:
            net:
                ipv4_address: 10.5.0.10
        restart: unless-stopped

networks:
    default:
        external: true
        name: Tyupkonet
    net:
        driver: bridge
        ipam:
            config:
                - subnet: 10.5.0.0/16

volumes:
    db-data: {}
    postgres:
    pgadmin:
    init:
